services:
  hotelservice:
    container_name: hotelservice
    environment:
      eureka.client.serviceUrl.defaultZone: "http://servi-loadb-1m010cvxc8v81-1110713425.us-east-2.elb.amazonaws.com/eureka" 
      DB_URL: "jdbc:postgresql://HotelDB:5432/Hotel"
    image: justadvancetechnology/hotelservice_p2.3
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      # x-aws-autoscaling:
      #   min: 1
      #   max: 2 
      #   cpu: 75
      resources:
        limits:
          cpus: '2'
          memory: 4Gb
    ports:
    - target: 80
      x-aws-protocol: http
      # - 80:80
    depends_on:
     - HotelDB
    restart: unless-stopped

  HotelDB:
    container_name: HotelDB
    image: postgres
    deploy:
      replicas: 1
      # x-aws-autoscaling:
      #   min: 1
      #   max: 2 
      #   cpu: 75
      resources:
        limits:
          cpus: '1'
          memory: 2Gb
    environment:
      DB_URL: "jdbc:postgresql://HotelDB:5432/"
      POSTGRES_DB: Hotel
      POSTGRES_USER: Hotel
      POSTGRES_PASSWORD: Hotel
    # ports:
    #   - "5551:5432"
    restart: unless-stopped