services:
  documentservice:
    container_name: documentservice
    # environment:
      # eureka.client.serviceUrl.defaultZone: "http://servi-loadb-1m010cvxc8v81-1110713425.us-east-2.elb.amazonaws.com/eureka" 
      # DB_URL: "jdbc:postgresql://HotelDB:5432/Hotel"
    image: justadvancetechnology/documentservice_p2.3.1patch
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      # replicas: 1
      x-aws-autoscaling:
        min: 1
        max: 2 
        cpu: 75
      resources:
        limits:
          cpus: '2'
          memory: 4Gb
    ports:
    - target: 80
      x-aws-protocol: http
      # - 80:80
    restart: unless-stopped

